name: pallets_taxi_driver_pannel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  iconsax:
  intl:
  get:
  http:
  shimmer:
  google_fonts: any
  shared_preferences: 
  cached_network_image: 
  flutter_smart_dialog:
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.1.0
  url_launcher: ^6.1.14
  flutter_html: any
  country_code_picker: ^3.0.0
  otp_text_field: ^1.1.3
  google_maps_flutter: ^2.0.10
  flutter_screenutil: ^5.9.0
  google_sign_in: ^6.2.1


    # Connectivity
  connectivity_plus: 

    # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.7
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/