// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDklgfSW703G-WVgfBhkzaxR3tdpUUnJYI',
    appId: '1:305241309976:android:5aaaa607f362c090a0946d',
    messagingSenderId: '305241309976',
    projectId: 'maps-flutter-59331',
    storageBucket: 'maps-flutter-59331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-0_tNFn3gs5ZYnnlc7QXNHDSefNxHi7w',
    appId: '1:305241309976:ios:dd6556d48fab9422a0946d',
    messagingSenderId: '305241309976',
    projectId: 'maps-flutter-59331',
    storageBucket: 'maps-flutter-59331.appspot.com',
    androidClientId: '305241309976-mjvtsr0j9qp5b453lkpuu5j19php4meb.apps.googleusercontent.com',
    iosClientId: '305241309976-g3e55udgn52u10glkhijjs33kn28gr2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.palletsTaxiDriverPannel',
  );
}
